# Use a full VM since we'll be using docker
#
# https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system
# https://docs.travis-ci.com/user/docker/

sudo: required
dist: trusty

language: c

addons:
  apt:
    packages:
      - awscli

services:
  - docker

# Note that `build-setup.sh` should be run before `docker build`.
# Without the packages installed on the host, specifically binfmt_support,
# the docker image will not be built correctly.  With the package installed,
# the docker image build will only produce warnings, but the end image will
# be functional.
install:
  - build-scripts/build-setup.sh
  - make shellcheck

# The whole process takes about 20 min.
# Note that the xz command uses --verbose to write things to tty as
# travis-ci will timeout the build otherwise.  xz takes a long time (more than)
# 10 minutes to run when zipping, and travis times out after 10 minutes.
script:
- make dist
# below lines used for debugging travis issues.
#- make build
#- ./run_build_env.sh ubuntu-xenial ./dist_full_img.sh

deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: eatsa-artifacts
  local-dir: pkg
  upload-dir: wise-display
  acl: private
  on:
    all_branches: true
    condition: $AWS_SECRET_ACCESS_KEY != ""
