# Use a full VM since we'll be using docker
#
# https://docs.travis-ci.com/user/reference/overview/#virtualisation-environment-vs-operating-system
# https://docs.travis-ci.com/user/docker/

sudo: required
dist: trusty

language: c

addons:
  apt:
    packages:
      - awscli

services:
  - docker

# Install ubuntu packages or custom services
#
# Note that build-setup.sh should be run before `docker build`.
# The `docker build` will give warnings from binfmt_misc, but may actually
# error out if binfmt_support package is not installed beforehand.
before_install:
  - curl https://s3.amazonaws.com/eatsa-packages/build-framework/build-framework-master-1.5.0.tgz -o /tmp/bf.tgz
  - tar --directory $HOME -xzf /tmp/bf.tgz
  - build-scripts/build-setup.sh
  - docker build -t eatsa-odroid-c2-rootfs:build-env-ubuntu-xenial dockerfiles/ubuntu-xenial
  - docker images

# Install any dependencies required
install:
  - shellcheck mk_build_env.sh run_build_env.sh build-scripts/build-setup.sh

script:
- echo "Run the build here?"

deploy:
  skip_cleanup: true
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: eatsa-packages
  local-dir: pkg
  upload-dir: image-odroid-c2
  acl: private
  on:
    all_branches: true
    condition: $AWS_SECRET_ACCESS_KEY != ""
