#!/bin/sh

set -e

PREREQ=""
prereqs() {
     echo "$PREREQ"
}

case $1 in
    prereqs)
         prereqs
         exit 0
         ;;
esac

# shellcheck disable=SC1091
. /usr/share/initramfs-tools/hook-functions

echo "Eatsa initrd hook start."

# klibc dependencies
for FILE in /lib/libacl* /lib/libblkid* /lib/libuuid* /lib/libdevmapper* /lib/libattr*
do
	if [ ! -e "${DESTDIR}/${FILE}" ] && ls "${FILE}" > /dev/null 2>&1
	then
		cp -a "${FILE}" "${DESTDIR}/${FILE}"
	fi
done

# udev dependencies
for FILE in /lib/udev/*_id
do
	copy_exec "${FILE}"
done

# Filesystem: btrfs
manual_add_modules btrfs

# Filesystem: ext3/ext4
manual_add_modules ext3
manual_add_modules ext4

# Filesystem: squashfs
copy_exec /sbin/losetup
manual_add_modules loop
manual_add_modules squashfs
manual_add_modules sqlzma
manual_add_modules unlzma

# Filesystem: aufs/overlayfs/unionfs
manual_add_modules aufs
manual_add_modules overlayfs
manual_add_modules unionfs

# Filesystem: vfat
manual_add_modules nls_cp437
manual_add_modules nls_iso8859-1
manual_add_modules nls_utf8
manual_add_modules vfat

# Hardware: usb
manual_add_modules sd_mod

auto_add_modules net

copy_exec /bin/mount /bin/mount.util-linux
copy_exec /sbin/wpa_supplicant
copy_exec /usr/bin/unsquashfs /bin
copy_exec /sbin/udevadm
copy_exec /usr/bin/wget /bin
copy_exec /sbin/blockdev
copy_exec /usr/bin/md5sum /bin

for n in libnl-3 libnl-genl-3 libdl libpcsclite libssl libdbus-1 libsystemd \
  liblzma libgcrypt libgpg-erro liblzo2 libz libm; do
  the_lib=$(find /lib -name "${n}.so.*" -type f)
    if [ -f "${the_lib}" ]; then
        copy_exec "${the_lib}"
    fi
done

echo "Finished Eatsa initrd hook."
