#!/bin/bash
# /deploy/wise-display/
#
# This was ported from wise-display builds for nuc_5ix and odroid_xu4
# However, using systemd-networkd seems to be better for ubuntu 16.04 and odroid-c2's

echo "Starting $0"

eth_mac=$(sed 's/://g' "/sys/class/net/$IFACE/address")
[ -z "$eth_mac" ] && eth_mac=unknown

if mount -r -L EATSACONF /mnt; then
    # shellcheck disable=SC1091
    [ -r /mnt/config.txt ] && . /mnt/config.txt
    umount /mnt
fi

if [ -n "$WISE_ROLE" ] && [ -n "$WISE_ID" ]; then
    myname="wise-${WISE_ROLE}${WISE_ID}"
else
    myname="wise-${eth_mac}"
fi

echo "# wise-ifpreup-hostname" > /etc/hosts
echo "127.0.0.1 localhost $myname" >> /etc/hosts
echo "$myname" > /etc/hostname
/bin/hostname $myname

echo "Finished $0"
